// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusteriBakiyeSeyri.DataAccess.Context;

#nullable disable

namespace MusteriBakiyeSeyri.DataAccess.Migrations
{
    [DbContext(typeof(MusteriBakiyeSeyriDb))]
    [Migration("20250902001413_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusteriBakiyeSeyri.Entities.Fatura.MusteriFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("fatura_tarihi");

                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fatura_tutari");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("odeme_tarihi");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("musteri_fatura_table", (string)null);
                });

            modelBuilder.Entity("MusteriBakiyeSeyri.Entities.Musteri.MusteriTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("char(255)")
                        .HasColumnName("UNVAN");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("musteri_tanim_table", (string)null);
                });

            modelBuilder.Entity("MusteriBakiyeSeyri.Entities.Fatura.MusteriFatura", b =>
                {
                    b.HasOne("MusteriBakiyeSeyri.Entities.Musteri.MusteriTanim", "MusteriTanim")
                        .WithMany("MusteriFaturalari")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusteriTanim");
                });

            modelBuilder.Entity("MusteriBakiyeSeyri.Entities.Musteri.MusteriTanim", b =>
                {
                    b.Navigation("MusteriFaturalari");
                });
#pragma warning restore 612, 618
        }
    }
}
